# -*- coding: utf-8 -*-
"""Task3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q-q3NpbsdmAdqKrI66Z0d8N-Ocxv68L9
"""

#Task 3

input_data = open('input3.txt','r')
output_data = open('output3.txt','w')

line1 = input_data.readline()

line2 = input_data.readline().split()
line2 = [int(i) for i in line2]

line3 = input_data.readline().split()
line3 = [int(i) for i in line3]

# I used selection sort, here the biggest number in the list is searched and shifted to the beginning of the list. However, if the marks were same, then I just shifted the smaller id.
for i in range(len(line2)-1):
  temp = i
  for j in range(i+1,len(line2)):
      if line3[temp] < line3[j]:
        line3[temp],line3[j] = line3[j],line3[temp]
        line2[temp],line2[j] = line2[j],line2[temp]

      elif line3[temp] == line3[j]:
        if line2[temp] > line2[j]:
          line2[temp],line2[j] = line2[j],line2[temp]

for i in range(len(line2)):
  print(f"ID: {str(line2[i])} Mark: {str(line3[i])}", file = output_data)